### ISSUE TITLE
Question: .NET Core projects are not currently supported .

### ISSUE THREAD

**Issue by maxild** [jcansdale/TestDriven.Net-Issues#143]
After reading #98 I see the v4.3+test runner supports firing single (test) methods (only) in netstandard 2.0 library projects. 

That is after adding a project like

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ObjectLayoutInspector\ObjectLayoutInspector.csproj" />
  </ItemGroup>

</Project>
```

to drive the 'tests'. 

I wouldn't exactly call this testing, but it would be great for what i call 'learning/interactive testing', where you fire off tests inside vs2017 to see how 3rd party code really works.

Is it correct that TestDriven.Net does not support .net core projects with

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.1;netcoreapp2.0;netcoreapp2.1</TargetFrameworks>
  </PropertyGroup>
```

any of the above .NET Core tfm's?

And is it also correct that this is not coming any time soon?

**Comment by billrob** [comment]
#106 Take a look.  Says no .net core support now and no timeframe.

**Comment by jcansdale** [comment]
I _really_ want to add support for .NET Core, the problem is blocking out some time to do it!

I've recently been modernizing the extension, which should make doing this easier. Going forward it's going to be a .vsix extension, with support for Visual Studio 2015 and up.

The protocol between the extension and test runner process is currently .NET Remoting based (which .NET Core doesn't support). I'm hoping to make this .json based so more common code can be used between .NET and Core.

There's still the issue of .NET Core test projects being applications which need to contain whatever execution code they require. I guess there could be a TestDriven.Net NuGet package with whatever test infrastructure is required. It's just not as seamless as with .NET.

I don't want to give any false expectations, but I haven't forgotten about this. It does look like .NET Core is the future and I definitely want to support it!

**Comment by maxild** [comment]
Thanks for the reply. .NET Core is definitely where innovation is happening. .Net standard (being about the least common denominator = integration) and .NET Framework is not getting the same amount of love:smile:

**Comment by jcansdale** [comment]
@maxild I wanted to let you know that I'm working on .NET Core support. You can find a track issue for it here #106. There are compatible versions linked at the bottom of the issue.  If try it, let me know how it goes. 😄

**Comment by maxild** [comment]
Super. I let you you know if things are working, if/when I try out the bits. Thanks for letting me know:smile:
