### ISSUE TITLE
Alternative or newer coverage options?

### ISSUE THREAD

**Issue by kzu** [jcansdale/TestDriven.Net-Issues#49]
The built-in NCover 1.5.8 is way old, and I'm getting the following error:

```
NCover.Console v1.5.8 - Code Coverage Analysis for .NET - http://ncover.org
...
Waiting for profiled application to connect...Connected
Configuring Profiler...
******************* Program Output *******************
Index was outside the bounds of the array.
```

Other than fixing the actual issue, I since NCover is now at v5.5, is there any chance they will allow TD.NET to include a more up-to-date version? How about integrating OpenCover+ReportGenerator otherwise?

**Comment by jcansdale** [comment]
Hi Daniel,

I've found that NCrunch works well alongside TestDriven.Net. They've turned out to be complementary and their interfaces don't get in each others way. This has me pretty sorted for continuous code coverage.

You should find the code coverage that comes with higher Visual Studio SKUs still works with TestDriven.Net. 'Test With > Code' Coverage and then select 'Show Code Coverage Coloring'.

These tools all seem to be in a state of flux now that .NET Core is here. Keeping them working has always been a huge pain. The NCover interface kept on changing until I finally gave up. Amazingly NCover v1.5.8 still works well enough that people would complain if I pulled it. :wink:

How are things with you? Have you been doing much .NET Core work?
