### ISSUE TITLE
Doesn't remove menu items when uninstalled

### ISSUE THREAD

**Issue by grokky1** [jcansdale/TestDriven.Net-Issues#97]
Until .NET Core support is incuded, I uninstalled TD to minimise the dozens of plugins I have running 😄 . I had the latest beta, on Win10 x64, with VS2017 with the latest update. I uninstalled from the control panel.

This menu option isn't removed though: `Tools > Abort Test Run`. Maybe there are others, but that's the only one I've noticed.

Also the options panel is still there: `Tools > Options` then in the tree on the left, it still has `TestDriven.Net`, and when clicking it shows `An error occurred loading this property page`.

**Comment by jcansdale** [comment]
Hmm, strange.

Could you have a look at the following location and let me know if there's anything there:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestDriven`
(you might have to replace `2017\Community` if you have a different version installed)

**Comment by grokky1** [comment]
Yes that directory contains: `TestDriven.VSPackage.dll` and `TestDriven.VSPackage.pkgdef`.

Note though that I didn't install VS to the standard location.

**Comment by jcansdale** [comment]
After deleting the files, you also need to "touch" the `Common7\IDE\Extensions\extensions.configurationchanged` file. This lets VS know that an extension has been added or removed and to update its configuration.

I'm working on making it so that you can at least execute .NET Core / Standard projects using .NET 4.6.1. That way you can quickly check the functionality works, even if you need to use a separate runner to execute with .NET Core.

**Comment by grokky1** [comment]
Uninstall: Yeah, that worked! Not that I'm really happy to remove TD mind you!

Core: that sounds awesome. Looking forward to it. I'll be your first guinea pig, erm beta tester.
